name: Test JBSM

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: windows-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Mostrar versión
        shell: cmd
        run: |
          type latest_version.txt

      - name: Ejecutar instalador
        shell: cmd
        run: |
          JBSM_installer.bat
